#!/bin/bash
PROGNAME=$(basename $1 .alan)
./alan $PROGNAME <$1 > $PROGNAME.ll
nl --body-numbering=a $PROGNAME.ll
llvm-as $PROGNAME.ll
llc -filetype=obj $PROGNAME.bc
g++ -no-pie $PROGNAME.o libalanstd.a
chmod +x a.out
rm $PROGNAME.{o,bc,ll} $LLFILENAME $OBJFILENAME
